// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("KafkaApplication")>]
[<assembly: AssemblyProductAttribute("KafkaApplication")>]
[<assembly: AssemblyDescriptionAttribute("Framework for kafka application. It contains computation expressions to help with building this kind of application and have in-build metrics, logging, parsing, etc..")>]
[<assembly: AssemblyVersionAttribute("8.0.0")>]
[<assembly: AssemblyFileVersionAttribute("8.0.0")>]
[<assembly: InternalsVisibleToAttribute("tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "KafkaApplication"
    let [<Literal>] AssemblyProduct = "KafkaApplication"
    let [<Literal>] AssemblyDescription = "Framework for kafka application. It contains computation expressions to help with building this kind of application and have in-build metrics, logging, parsing, etc.."
    let [<Literal>] AssemblyVersion = "8.0.0"
    let [<Literal>] AssemblyFileVersion = "8.0.0"
    let [<Literal>] InternalsVisibleTo = "tests"
